groups:
  - name: cineminha
    rules:
      - alert: usoMemoriaMaior70Porcento
        expr: 100 * (1 - (jvm_memory_used_bytes{area="heap"} / jvm_memory_max_bytes{area="heap"})) > 70
        for: 5m
        labels:
          app: cineminha
          severity: critical
          group: backend-cineminha
          env: production
        annotations:
          title: Uso de memória RAM
          summary: O uso de memória é maior que 70%
          description: O uso de memória é maior que 70%
