server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:~/bancodigital
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,configprops,prometheus"
  info:
    env:
      enabled: true

info:
  application:
    name: Banco Digital com métricas
    description: Aplicação feita para Treinamento de Métricas e monitoramento
