server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:~/pedidos
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

management:
  health:
    diskSpace:
      enabled: false
    ping:
      enabled: false
  endpoint:
      health:
        show-details: always
  endpoints:
    web:
      exposure:
        include: "health,scheduledtasks"
